name: Maven Publish Snapshot

on:
  push:
    branches: [master]

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Develop
        uses: actions/checkout@v2
        with:
          ref: 'develop'

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Check Environment
        run: |
          uname -a
          git --version
          mvn -version
          java -version

      - name: Build Artifact
        env:
          GITHUB_ACTOR: snapshot-workflow
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn clean verify -B --file pom.xml -s $GITHUB_WORKSPACE/settings.xml

      - name: Reconfigure Maven settings for Deploy
        run: |
          sed -i 's/github/github-snapshots/g' $GITHUB_WORKSPACE/settings.xml
          cat $GITHUB_WORKSPACE/settings.xml

      - name: Publish Artifact
        env:
          GITHUB_ACTOR: snapshot-workflow
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn deploy -s $GITHUB_WORKSPACE/settings.xml
